#!/usr/bin/env bash

# install the nginx web server

apt-get update

apt- get -y install nginx

# Configure Nginx to listen on port 80
echo "server {
	listen 80;
	location / {
		echo 'Hello World!';
} }" > /etc/nginx/sites-available/default
service nginx restart
