#!/usr/bin/env bash
# install the nginx web server
# the nginx should listen on port 80

apt-get -y update
apt-get -y install nginx
# Configure Nginx to listen on port 80
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.ht
service nginx start
