#!/usr/bin/env bash
# install the nginx web server
# the nginx should listen on port 80

sudo apt update
sudo apt install -y nginx
sudo service nginx start

# Configure Nginx to listen on port 80
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

service nginx restart
