#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
cat <<EOF > /etc/nginx/sites-available/redirect_me
server {
	listen 80;
	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}
}
EOF
service nginx reload
