#!/usr/bin/env bash

#start the service
sudo service nginx start

nginx -t

#configure to listen on port 80
sudo sed -i 's/listen\s*\(.*\):8080;/listen 80;/' /etc/nginx/nginx.conf

# Restart Nginx
sudo service nginx restart
