#!/usr/bin/env bash
# This script loops from 1 to 10 and displays different messages based on the iteration number provided

j=1
while [ $j -le 10 ]
do
	if [ $j -eq 4 ];
then
		echo "bad luck"
	elif [ $j -eq 8 ];
then
		echo "good luck"
	else
		echo "Best School"
	fi
	j=$((j+1))
done
