#!/usr/bin/env bash
# a script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu
ssh -i ~/.ssh/school ubuntu@52.91.125.181
ssh -i ~/.ssh/school ubuntu@52.205.83.140
